### ISSUE TITLE
Sheetsu -> google sheets directly

### ISSUE THREAD

**Issue by acabunoc** [xmatthewx/network-pulse#3]
You can migrate away from sheetsu & use the google sheets api directly with the code here:
https://github.com/mozilla/clubs-events/blob/gh-pages/js/app.js#L33

cc @OpenMatt

Let me know if you have any questions, I did the same thing here: https://github.com/acabunoc/open-canvas

**Comment by mmmavis** [comment]
@xmatthewx do you think we can make this [spreadsheet](https://docs.google.com/spreadsheets/d/1vmYQjQ9f6CR8Hs5JH3GGJ6F9fqWfLSW0S4dz-t2KTF4/edit#gid=922457769) public?

**Comment by xmatthewx** [comment]
Done ✅

**Comment by xmatthewx** [comment]
@mmmavis – had a chance to look at this yet?
